### ISSUE TITLE
Another duktape port

### ISSUE THREAD

**Issue by negativekelvin** [pepe79/esp32-javascript#1]
https://github.com/nkolban/duktape-esp32

Just wanted to let you know.  You can close this.

**Comment by pepe79** [comment]
Hey @negativekelvin ,
thanks, I already knew about it, when I created this repo. The goal is to have ESP32-JS-support enriched with basic non-blocking networking and a plugin-concept for users to easily extend the eventloop or provide higher level functionality. I will update the Readme soon.
